services:
  outlandish_oowp.post_manager:
    class: Outlandish\OowpBundle\Oowp
  outlandish_oowp.query_manager:
    class: Outlandish\OowpBundle\Manager\QueryManager
    arguments: [@outlandish_oowp.post_manager]

  outlandish_oowp.register_post_types:
    class: Outlandish\OowpBundle\EventListener\RegisterPostTypes
    calls:
      - [ setPostManager, [@outlandish_oowp.post_manager]]
    tags:
      - name: kernel.event_listener
        event: kernel.request
        method: onKernelRequest

  outlandish_oowp.helper.menu:
    class: Outlandish\OowpBundle\Helper\MenuHelper
    arguments: [@outlandish_oowp.query_manager, @outlandish_oowp.post_manager, @templating]
    tags:
      - name: templating.helper
        alias: menu
  outlandish_oowp.helper.paginator:
    class: Outlandish\OowpBundle\Helper\PaginatorHelper
    arguments: [@outlandish_oowp.query_manager]
    tags:
      - name: templating.helper
        alias: paginator