services:

  outlandish_oowp.post_manager:
    class: Outlandish\OowpBundle\Manager\PostManager

  # override Routemaster query manager
  outlandish_routemaster.query_manager:
    class: Outlandish\OowpBundle\Manager\QueryManager
    arguments: [@outlandish_oowp.post_manager]

  # create alias in case you forget which bundle this is from
  outlandish_oowp.query_manager:
    alias: outlandish_routemaster.query_manager

  # register post types on kernel request or on WP init hook
  outlandish_oowp.register_post_types:
    class: Outlandish\OowpBundle\EventListener\RegisterPostTypes
    arguments: [@outlandish_oowp.post_manager]
    tags:
      - name: kernel.event_listener
        event: kernel.request
        method: onKernelRequest
      - name: kernel.event_listener
        event: outlandish_routemaster.wp_init
        method: onKernelRequest

  # inject JS/CSS assets into WP admin pages
  outlandish_oowp.admin_assets:
    class: Outlandish\OowpBundle\EventListener\AdminAssets
    arguments: [@templating.engine.php]
    tags:
      - name: kernel.event_listener
        event: outlandish_routemaster.wp_init
        method: onInit

  outlandish_oowp.helper.menu:
    class: Outlandish\OowpBundle\Helper\MenuHelper
    arguments: [@outlandish_routemaster.query_manager, @outlandish_oowp.post_manager, @templating]
    tags:
      - name: templating.helper
        alias: menu

  outlandish_oowp.helper.paginator:
    class: Outlandish\OowpBundle\Helper\PaginatorHelper
    arguments: [@outlandish_routemaster.query_manager]
    tags:
      - name: templating.helper
        alias: paginator

  outlandish_oowp.helper.wp:
    class: Outlandish\OowpBundle\Helper\WordpressHelper
    tags:
      - name: templating.helper
        alias: wp