services:
    outlandish.oowp:
        class: Outlandish\OowpBundle\Oowp
#    outlandish.oowp:
#        class: Outlandish\OowpBundle\Oowp
#        tags:
#        - name: kernel.event_listener
#          event: kernel.request
#          method: onKernelRequest